### ISSUE TITLE
Opening Messenger on Android v4.4.2 fails

### ISSUE THREAD

**Issue by Compulsed** [intercom/intercom-cordova#123]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.19
  - Cordova Version: 6.3.1 
  - Cordova Android Version: 5.1.1
  - iOS/Android OS version: 4.4.2 (Api 19)
  - iOS/Android Device: Samsung SM-T310

## Expected behavior

Opening Intercom Messenger, shows the messenger window
(application builds and intercom icon shows up correctly)

## Actual behavior

Clicking on the intercom icon to open the chat causes application to stop responding

## Steps to reproduce
 1. Open Application
 2. Click Intercom Icon

## Other
- All native views now cause the application to crash
- Android Support Library v23.2.1
- Android Support Repository v40
- android-minSdkVersion = 17
- It appears all our other devices >= Android 5 work fine

## Logs

```
11-24 14:07:27.231 8428-8428/com.app.qa E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.app.qa, PID: 8428
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.qa/io.intercom.android.sdk.activities.IntercomMessengerActivity}: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:174)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:146)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
                                                                             at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:726)
                                                                             at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                                                                             at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                                             at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                             at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                             at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
                                                                             at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                                                                             at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                                                                             at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
                                                                             at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
                                                                             at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:21)
                                                                             at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:66)
                                                                             at android.app.Activity.performCreate(Activity.java:5458)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:174) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:146) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5593) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by ronocod** [comment]
Can you try updating to the latest Cordova Android version? There's a good chance it will fix this.

**Comment by Compulsed** [comment]
Updating Android Cordova from 5.1.0 to 5.2.2 fixed the issue!

Hooray!

**Comment by ronocod** [comment]
Great 😄
