### ISSUE TITLE
Unable to start activity IntercomMessengerActivity

### ISSUE THREAD

**Issue by abunour22** [intercom/intercom-cordova#131]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.22
  - iOS/Android OS version: Android 4.4.2
  - iOS/Android Device: SAMSUNG GT-N7100
  - Cordova android : v6.1.0 
  - minSDKVersion : 16
  - targetSDKVersion : 19 , 20 , 21 , 22 , 23

## Expected behavior
Intercom messenger should start.

## Actual behavior
My App Crashed.

## Logs
```
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.MyAppCompany.myapp/io.intercom.android.sdk.activities.IntercomMessengerActivity}: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:726)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
	at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:21)
	at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:5451)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
```

**Comment by bboyle18** [comment]
Hi @abunour22 👋

Thanks for getting in touch. 
You need to update to the latest version of Android Cordova. Take a look at this issue for more info https://github.com/intercom/intercom-cordova/issues/123

Cheers

Brian

**Comment by abunour22** [comment]
It's the latest version Cordova android v6.1.0 
https://cordova.apache.org/announcements/2016/11/07/android-release.html

I don't think the problem is Android Cordova Version ?!

**Comment by bboyle18** [comment]
Hi @abunour22 

I'm sorry this didn't fix your issue. 
Can you tell me if you are using just plain Cordova or Ionic2 to build your app?

Thanks

Brian

**Comment by abunour22** [comment]
I'm using https://cocoon.io which is as i know plain Cordova

**Comment by DaleCantwell** [comment]
@abunour22 do you know what version of gradle you are using?

**Comment by bboyle18** [comment]
Hi @abunour22 👋 
Just wondering if you have solved this issue yet? If not, can you provide us with the version of gradle that you are using so that we can investigate this further and find a solution for you?

Thanks!

Brian

**Comment by bboyle18** [comment]
Closing as no response on issue. @abunour22 Feel free to reopen if you have more info to add.
Brian
