### ISSUE TITLE
Android Push not working while app is closed (not background)

### ISSUE THREAD

**Issue by Mohamed-Habshey** [intercom/intercom-cordova#134]
Hi Everyone,

i tried to get push notification to work with my ionic1 app via intercom, 
the android app crash when i send a message while the app is closed however works fine if the app in the background, i even tried to debug the issue and used your simple app i got the same result.
any ideas?

Thanks in advance
Regards
Mohamed

## Version info
  - Intercom for Cordova/PhoneGap version: intercom@3.0.23, cordova 6.4.0, cordova-android@6.1.1
  - iOS/Android OS version: android 4.2.2
  - iOS/Android Device: emulator and real device SM-G900F

## Expected behavior
1. get a push message when app closed (not in the background)
## Actual behavior
1. app crash
## Steps to reproduce
 1. login to your app
 2. make sure you closed the app not in the background
 3. send message from intercom
4. app crash

## Logs

adb logcat 
```
W/dalvikvm( 6087): threadid=10: thread exiting with uncaught exception (group=0x5cca5b20)
I/Process ( 6087): Sending signal. PID: 6087 SIG: 9
D/BstCommandProcessor-Application( 1905): Application crash has been observed.
W/BstCommandProcessor-Application( 1905): in sendHttpRequest, requestType is of CRASH_APP type but one of the requiredInfo is NULL, crashedApp = com.bluestacks.BstCommandProcessor.BstCrashedAppInfo@2e730208
D/BstCommandProcessor-Application( 1905): in sendHttpRequest, request to send to (fqdn): http://10.0.2.2:2861/AppCrashedInfo
D/BstCommandProcessor-Application( 1905): data: {"packageName":"io.intercom.cordova.sample","shortPackageName":"io.intercom.cordova.sample","versionCode":1,"versionName":"0.0.1"}
D/AndroidRuntime( 6087): procName from cmdline: io.intercom.cordova.sample
E/AndroidRuntime( 6087): in writeCrashedAppName, pkgName :io.intercom.cordova.sample
D/AndroidRuntime( 6087): file written successfully with content: io.intercom.cordova.sample StringBuffer : ;io.intercom.cordova.sample
E/AndroidRuntime( 6087): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 6087): Process: io.intercom.cordova.sample, PID: 6087
E/AndroidRuntime( 6087): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
E/AndroidRuntime( 6087):        at android.os.Handler.<init>(Handler.java:200)
E/AndroidRuntime( 6087):        at android.os.Handler.<init>(Handler.java:114)
E/AndroidRuntime( 6087):        at io.intercom.android.sdk.ResetManager.<init>(ResetManager.java:33)
E/AndroidRuntime( 6087):        at io.intercom.android.sdk.Injector.getResetManager(Injector.java:186)
E/AndroidRuntime( 6087):        at io.intercom.android.sdk.Injector.getLifecycleTracker(Injector.java:171)
E/AndroidRuntime( 6087):        at io.intercom.android.sdk.Injector.initWithAppCredentials(Injector.java:68)
E/AndroidRuntime( 6087):        at io.intercom.android.sdk.Injector.init(Injector.java:57)
E/AndroidRuntime( 6087):        at io.intercom.android.sdk.push.IntercomPushClient.handlePush(IntercomPushClient.java:92)
E/AndroidRuntime( 6087):        at io.intercom.android.sdk.gcm.IntercomGcmListenerService.onMessageReceived(IntercomGcmListenerService.java:13)
E/AndroidRuntime( 6087):        at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
E/AndroidRuntime( 6087):        at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
E/AndroidRuntime( 6087):        at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
E/AndroidRuntime( 6087):        at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
E/AndroidRuntime( 6087):        at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
E/AndroidRuntime( 6087):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 6087):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 6087):        at java.lang.Thread.run(Thread.java:841)
I/ActivityManager( 1712): Process io.intercom.cordova.sample (pid 6087) has died.
```

**Comment by Mohamed-Habshey** [comment]
update: actually this was fixed in intercom-android@3.0.18 
i had upgraded and it worked fine i think this pr  #135  will solve the problem
thanks 🙂

**Comment by ronocod** [comment]
Yes, we're working on this now, it should be fixed in the next release 🙂

**Comment by ronocod** [comment]
3.0.24 is released with this fix.

**Comment by Mohamed-Habshey** [comment]
@ronocod  Thanks,  have a nice day.
Regards :slightly_smiling_face:
