### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by sisodiakaran** [intercom/intercom-cordova#14]
Hello,

I installed plugin using following comand:`$ phonegap plugin add cordova-plugin-intercom --variable APP_ID="<my_app_key>" --variable ANDROID_API_KEY="android_sdk-<my_api_key>"`

But while on run/build I am getting `UNEXPECTED TOP-LEVEL EXCEPTION`. Below is stack trace.

```
Executing tasks: [:CordovaLib:generateDebugSources, :CordovaLib:generateDebugTestSources, :generateDebugSources, :generateDebugTestSources]

Configuration on demand is an incubating feature.
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:preDebugTestBuild
:CordovaLib:prepareDebugTestDependencies
:CordovaLib:compileDebugTestAidl UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:CordovaLib:assembleDebug UP-TO-DATE
:CordovaLib:processDebugTestManifest UP-TO-DATE
:CordovaLib:compileDebugTestRenderscript UP-TO-DATE
:CordovaLib:generateDebugTestBuildConfig UP-TO-DATE
:CordovaLib:generateDebugTestAssets UP-TO-DATE
:CordovaLib:mergeDebugTestAssets UP-TO-DATE
:CordovaLib:generateDebugTestResValues UP-TO-DATE
:CordovaLib:generateDebugTestResources UP-TO-DATE
:CordovaLib:mergeDebugTestResources UP-TO-DATE
:CordovaLib:processDebugTestResources UP-TO-DATE
:CordovaLib:generateDebugTestSources UP-TO-DATE
:preBuild
:preDebugBuild
:checkDebugManifest
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV42200Library
:prepareComGoogleAndroidGmsPlayServicesBase750Library
:prepareComGoogleAndroidGmsPlayServicesGcm750Library
:prepareIoIntercomAndroidIntercomSdk113Library
:prepareIoIntercomAndroidIntercomSdkBase113Library
:prepareIoIntercomAndroidIntercomSdkGcm113Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:mergeDebugResources
/media/media/Projects/MobileBinarySignals/MobileApp/BinarySignals/platforms/android/res/drawable/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processDebugManifest
:processDebugResources
:generateDebugSources
:preDebugTestBuild
:prepareDebugTestDependencies
:compileDebugTestAidl UP-TO-DATE
:processDebugTestManifest UP-TO-DATE
:compileDebugTestRenderscript UP-TO-DATE
:generateDebugTestBuildConfig UP-TO-DATE
:generateDebugTestAssets UP-TO-DATE
:mergeDebugTestAssets UP-TO-DATE
:generateDebugTestResValues UP-TO-DATE
:generateDebugTestResources UP-TO-DATE
:mergeDebugTestResources UP-TO-DATE
:processDebugTestResources UP-TO-DATE
:generateDebugTestSources UP-TO-DATE

BUILD SUCCESSFUL

Total time: 17.313 secs
Executing tasks: [:CordovaLib:generateDebugSources, :CordovaLib:generateDebugTestSources, :generateDebugSources, :generateDebugTestSources]

Configuration on demand is an incubating feature.
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:preDebugTestBuild
:CordovaLib:prepareDebugTestDependencies
:CordovaLib:compileDebugTestAidl UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:CordovaLib:assembleDebug UP-TO-DATE
:CordovaLib:processDebugTestManifest UP-TO-DATE
:CordovaLib:compileDebugTestRenderscript UP-TO-DATE
:CordovaLib:generateDebugTestBuildConfig UP-TO-DATE
:CordovaLib:generateDebugTestAssets UP-TO-DATE
:CordovaLib:mergeDebugTestAssets UP-TO-DATE
:CordovaLib:generateDebugTestResValues UP-TO-DATE
:CordovaLib:generateDebugTestResources UP-TO-DATE
:CordovaLib:mergeDebugTestResources UP-TO-DATE
:CordovaLib:processDebugTestResources UP-TO-DATE
:CordovaLib:generateDebugTestSources UP-TO-DATE
:preBuild
:preDebugBuild
:checkDebugManifest
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJava UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase750Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm750Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdk113Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdkBase113Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdkGcm113Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:preDebugTestBuild
:prepareDebugTestDependencies
:compileDebugTestAidl UP-TO-DATE
:processDebugTestManifest UP-TO-DATE
:compileDebugTestRenderscript UP-TO-DATE
:generateDebugTestBuildConfig UP-TO-DATE
:generateDebugTestAssets UP-TO-DATE
:mergeDebugTestAssets UP-TO-DATE
:generateDebugTestResValues UP-TO-DATE
:generateDebugTestResources UP-TO-DATE
:mergeDebugTestResources UP-TO-DATE
:processDebugTestResources UP-TO-DATE
:generateDebugTestSources UP-TO-DATE

BUILD SUCCESSFUL

Total time: 3.023 secs
Executing tasks: [:assembleDebug]

Configuration on demand is an incubating feature.
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJava UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase750Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm750Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdk113Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdkBase113Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdkGcm113Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava UP-TO-DATE
:preDexDebug UP-TO-DATE
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/var/sdk/build-tools/22.0.1/dx --dex --no-optimize --output /media/media/Projects/MobileBinarySignals/MobileApp/BinarySignals/platforms/android/build/intermediates/dex/debug --input-list=/media/media/Projects/MobileBinarySignals/MobileApp/BinarySignals/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.229 secs
```

**Comment by jtreanor** [comment]
Hi @sisodiakaran,

It looks like another plugin you are using also requires the Android support library. Unfortunately if they just include a jar there is not much we can do to avoid conflicting with them. 

However; you may be able to work around it by changing the command you use to install it to this:

```
phonegap plugin add https://github.com/intercom/intercom-cordova.git#no_support_library --variable APP_ID="<my_app_key>" --variable ANDROID_API_KEY="android_sdk-<my_api_key>"
```

This is a slightly modified version of our plugin which does not include the Android support library.

**Comment by sisodiakaran** [comment]
Hi @jtreanor,

I have installed the modified version but it still throwing error:

```
Error:Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/var/sdk/build-tools/22.0.1/dx --dex --no-optimize --output /media/media/Projects/MobileBinarySignals/MobileApp/BinarySignals/platforms/android/build/intermediates/dex/debug --input-list=/media/media/Projects/MobileBinarySignals/MobileApp/BinarySignals/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by jtreanor** [comment]
Ah. It looks like there is also a conflict with Google Play services.

Would you mind telling me what other plugins you are using?

**Comment by sisodiakaran** [comment]
The other plugin that might be conflicting is: https://github.com/realtime-framework/CordovaPush

**Comment by jtreanor** [comment]
Thanks @sisodiakaran,

Could you try this command:

```
phonegap plugin add https://github.com/intercom/intercom-cordova.git#no_play_services --variable APP_ID="<my_app_key>" --variable ANDROID_API_KEY="android_sdk-<my_api_key>"
```

**Comment by sisodiakaran** [comment]
Thanks @jtreanor,

The `#no_play_services` workaround worked for me.

Thanks again...

**Comment by slorber** [comment]
I have the same problem, and the 2 plugins I use are:

```
    <plugin name="phonegap-plugin-push"                     spec="1.2.2" />
    <plugin name="cordova-plugin-intercom"                  spec="1.0.8"  >
```


Currently I don't care so much about intercom push, so I did not use the fork you provided and decided to go with the up to date `phonegap-plugin-push` plugin.

This `phonegap-plugin-push` plugin uses `android-support-v13.jar`

This plugin uses transitively: `intercom-sdk:1.1.3` > `play-services-gcm:7.5.0` > `play-services-base:7.5.0` > `support-v4:22.0.0`

So there's a conflict


I tried using: `<plugin name="cordova-plugin-intercom"                  spec="https://github.com/intercom/intercom-cordova.git#no_play_services">`

And even removed all other plugins.

But I got the error:

```
/home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:73: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/sebastien/Desktop/devhome/install/adt-bundle-linux-x86_64-20140321/sdk/build-tools/22.0.1/aapt package -f --no-crunch -I /home/sebastien/Desktop/devhome/install/adt-bundle-linux-x86_64-20140321/sdk/platforms/android-22/android.jar -M /home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/intermediates/res/debug -A /home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/intermediates/assets/debug -m -J /home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/generated/source/r/debug -F /home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package co.stample -0 apk --output-text-symbols /home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/intermediates/symbols/debug
  Error Code:
  	1
  Output:
  	/home/sebastien/Desktop/Stample-react/cordova/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:73: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').
```

**Comment by slorber** [comment]
But it works fine with `no_support_library` cool !

Maybe it should be documented in the "push" section of the readme

How will these 2 branches be supported in the long run? 
I care about the branch being updated without us noticing it, producing potential production regressions 
The solution could be  that I fork this branch and tag it myself?


Here's my full plugin working setting:


```xml
    <engine name="android" spec="4.0.2" />

    <plugin name="cordova-plugin-device"                    spec="1.0.1" />
    <plugin name="cordova-plugin-console"                   spec="1.0.1" />
    <plugin name="cordova-plugin-whitelist"                 spec="1.1.0" />
    <plugin name="uk.co.whiteoctober.cordova.appversion"    spec="https://github.com/whiteoctober/cordova-plugin-app-version.git#0.1.7" />
    <plugin name="cordova-plugin-crosswalk-webview"         spec="1.2.0" />
    <plugin name="cordova-plugin-statusbar"                 spec="1.0.1" />
    <plugin name="cordova-plugin-screen-orientation"        spec="1.3.6" />
    <plugin name="cordova-plugin-splashscreen"              spec="2.1.0" />
    <plugin name="cordova-plugin-inappbrowser"              spec="1.0.1" />
    <plugin name="cordova-plugin-globalization"             spec="1.0.1" />
    <plugin name="org.apache.cordova.camera"                spec="0.3.6" />
    <plugin name="phonegap-plugin-push"                     spec="1.2.2" />
    <plugin name="cordova-plugin-intercom"                  spec="https://github.com/intercom/intercom-cordova.git#no_support_library">
        <variable name="APP_ID" value="z" />
        <variable name="IOS_API_KEY" value="ios_sdk-y" />
        <variable name="ANDROID_API_KEY" value="android_sdk-z" />
    </plugin>
```

**Comment by jtreanor** [comment]
Hi @slorber,

We are working out the best way to support excluding play services and the support library in the long term.
I'll keep this updated as we finalise the solution.

**Comment by slorber** [comment]
thanks
