### ISSUE TITLE
Can't install version 3.1.0

### ISSUE THREAD

**Issue by rubenstolk** [intercom/intercom-cordova#147]
```
Installing "cordova-plugin-intercom" for ios
Failed to install 'cordova-plugin-intercom':Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/.../platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
Error: pod: Command failed with exit code 1
```

Installing `cordova plugin add cordova-plugin-intercom@3.0.26` is successful, so the issue is since the latest version only.

**Comment by jtreanor** [comment]
This seems to be the same problem described in https://github.com/intercom/intercom-cordova/issues/146. It is not an issue with the plugin, but with the CocoaPods repo being out of date.

If you run `pod repo update` and try again it should work as expected.
