### ISSUE TITLE
Android 4.4.2 crash on opening chat

### ISSUE THREAD

**Issue by MocanuMarius** [intercom/intercom-cordova#186]
Crashing when opening chat

```
AndroidRuntime( 1371): FATAL EXCEPTION: main
E/AndroidRuntime( 1371): Process: zzzzz.app, PID: 1371
E/AndroidRuntime( 1371): java.lang.RuntimeException: Unable to start activity ComponentInfo{zzzzz.app/io.intercom.android.sdk.activities.IntercomMessengerActivity}: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
E/AndroidRuntime( 1371): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
E/AndroidRuntime( 1371): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/AndroidRuntime( 1371): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 1371): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 1371): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1371): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1371): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 1371): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1371): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1371): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 1371): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 1371): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1371): Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
E/AndroidRuntime( 1371): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:726)
E/AndroidRuntime( 1371): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
E/AndroidRuntime( 1371): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
E/AndroidRuntime( 1371): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
E/AndroidRuntime( 1371): 	at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:21)
E/AndroidRuntime( 1371): 	at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:70)
E/AndroidRuntime( 1371): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 1371): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 1371): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
E/AndroidRuntime( 1371): 	... 11 more
W/ActivityManager(  376):   Force finishing activity zzzzzz.app/io.intercom.android.sdk.activities.IntercomMessen
```

## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.26
  - iOS/Android OS version: Android 4.4.2 and below.

**Comment by skylerwshaw** [comment]
@MocanuMarius thanks for the report. Can you please share the additional information?:

* How many times have you seen this crash?
* On how many individual devices? 
* Are you able to update to 3.2.2, our latest Android SDK version?

**Comment by MocanuMarius** [comment]
@skylerwshaw still doesn't work for 3.2.2, but i will try that version and see if the error is the same ( didnt open logcat for that one) . 
Tested on Emulator (4.4.2) and 1 device that uses 4.4.2. Tried with emulator 5.1.1 and device 5.1.1 and it works fine.

I will come back with a 3.2.2 error, i didn't want to use that version since it forces target 25 SDK.

**Comment by MocanuMarius** [comment]
@skylerwshaw yep, same error for 3.2.2 , copy paste :)

**Comment by skylerwshaw** [comment]
@MocanuMarius This issue appears to have been raised in https://issuetracker.google.com/issues/37107179

Which version of Gradle are you using? Can you share the relevant `build.gradle` dependency details? Feel free to start a conversation through your Intercom dashboard and ask for me if you would like to keep this private.

**Comment by MocanuMarius** [comment]
@skylerwshaw no need to keep it private if it could help others.
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
   }
```
```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    compile "com.android.support:support-v4:24.1.1+"
}

```

**Comment by skylerwshaw** [comment]
Hi @MocanuMarius, the issue is your use of an outdated version of Gradle:
`classpath 'com.android.tools.build:gradle:1.5.0'`

You will want to ensure you're using the latest Gradle, currently 3.5

**Comment by MocanuMarius** [comment]
@skylerwshaw i will try it out and see what can be done, thanks for this . I will close the issue myself if it works as per your input.

**Comment by MocanuMarius** [comment]
@skylerwshaw seems like everytime i change it to 3.5 the builder switches it back to 2.2.1

**Comment by MocanuMarius** [comment]
@skylerwshaw 

The crash was fixed, i did the following things:
Upgrade cordova's android platform:

` - cordova platform update android`

Then it asked for gradle to be available ( i think they changed how they use gradle at some point in cordova's updates ) , so i installed it on ubuntu with apt-get and adding android's gradle repository.

I think it uses gradle 3.3.0 now, seems to no crash anymore.

**Comment by skylerwshaw** [comment]
Great to hear! Thanks for the update on your resolution @MocanuMarius.
