### ISSUE TITLE
Plugin not work on Android platform

### ISSUE THREAD

**Issue by sdey0081** [intercom/intercom-cordova#195]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.2.2
  - iOS/Android OS version:
  - iOS/Android Device:

## Steps to reproduce
 1. Generate a blank Ionic project.
``` 
ionic start ionApp blank
```
 2. Install intercom plugin 
```
ionic cordova plugin add cordova-plugin-intercom
npm install @ionic-native/intercom
```
 3. Update `config.xml` (set push-type to fcm), and add `google-services.json` to the project root.
```
<preference name="intercom-app-id" value="dprxnrce" />
<preference name="intercom-ios-api-key" value="xxx" />
<preference name="intercom-android-api-key" value="xxx" />
<preference name="intercom-android-push-type" value="FCM" />
```
 4. Build android apk.
```
ionic cordova build  android --release --prod
```

## Logs
```
[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
[ERROR] An error occurred while running cordova build android --release (exit code 1):
        (truncated) ... adleLauncher$1.execute(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        FAILURE: Build failed with an exception.
        * Where:
        Script 'E:\ionApp\platforms\android\cordova-plugin-intercom\starter-intercom.gradle' line: 41
        * What went wrong:
        A problem occurred evaluating script.
        > Failed to capture snapshot of output files for task 'copyGoogleServices' property 'destinationDir' during up-to-date check.
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
````

**Comment by skylerwshaw** [comment]
Thank you for the reproduction instructions. Unfortunately I was unable to reproduce the issue. Which version of ionic are you using? Please be sure to use `3.7.0` which is the current version. It's also unclear why `npm install @ionic-native/intercom` was run. Additionally, be sure your widget id matches your the project id of your google services file.

My successful reproduction steps:
```bash
$ npm install -g cordova ionic
$ ionic -v
3.7.0
$ ionic start ionApp blank
$ cd ./ionApp
$ cordova plugin add cordova-plugin-intercom
```
Note: I did not run `npm install @ionic-native/intercom`, which is unnecessary.

Add the following to `config.xml`:
```
<preference name="intercom-app-id" value="xxx" />
<preference name="intercom-ios-api-key" value="xxx" />
<preference name="intercom-android-api-key" value="xxx" />
<preference name="intercom-android-push-type" value="FCM" />
```
Add `google-services.json` to root directory of project
Change `<widget id="com.someapp.something">` id value to match the reverse dns name of your `google-services.json` project.
```
$ ionic cordova build  android --release --prod
```
The above resulted in a build that ran nominally on both simulator and physical device.
