### ISSUE TITLE
Application crashes when using cordova plugin

### ISSUE THREAD

**Issue by fdtsybouk** [intercom/intercom-cordova#67]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.5
  - iOS/Android OS version: 5.1.1
  - iOS/Android Device: Xiaomi Mi4 LTE

## Expected behavior
Application is functioning normal.

## Actual behavior
Application crushes on startup.

## Steps to reproduce
 1. Install plugin
 2. Build & run application on device

## Logs
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.agroweblab.supplant.ionic/com.agroweblab.supplant.ionic.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.intercom.android.sdk.api.Api io.intercom.android.sdk.Injector.getApi()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'io.intercom.android.sdk.api.Api io.intercom.android.sdk.Injector.getApi()' on a null object reference
       at io.intercom.android.sdk.IntercomBridge$1.run(IntercomBridge.java:39)
       at android.app.Activity.runOnUiThread(Activity.java:5293)
       at io.intercom.android.sdk.IntercomBridge.pluginInitialize(IntercomBridge.java:36)
       at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
       at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
       at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
       at org.apache.cordova.PluginManager.init(PluginManager.java:87)
       at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
       at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
       at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
       at com.agroweblab.supplant.ionic.MainActivity.onCreate(MainActivity.java:32)
       at android.app.Activity.performCreate(Activity.java:5990)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

## Android API version
 <preference name="android-minSdkVersion" value="17"/>

## Plugins installed 
  <engine name="android" spec="~5.1.1"/>
  <plugin name="cordova-plugin-device" spec="~1.1.2"/>
  <plugin name="cordova-plugin-dialogs" spec="~1.2.1"/>
  <plugin name="cordova-plugin-inappbrowser" spec="~1.4.0"/>
  <plugin name="ionic-plugin-keyboard" spec="~2.2.0"/>
  <plugin name="cordova-plugin-splashscreen" spec="~3.2.2"/>
  <plugin name="onesignal-cordova-plugin" spec="~1.12.5"/>
  <plugin name="cordova-fabric-plugin" spec="~1.0.8"/>
  <plugin name="cordova-plugin-network-information" spec="~1.2.1"/>
  <plugin name="cordova-plugin-statusbar" spec="~2.1.3"/>
  <plugin name="cordova-plugin-email-composer" spec="~0.8.3"/>
  <plugin name="cordova-plugin-intercom" spec="~3.0.5"/>

**Comment by jtreanor** [comment]
This is fixed in [3.0.6](https://github.com/intercom/intercom-cordova/releases/tag/3.0.6).
